# SPDX-License-Identifier: GPL-2.0
#
# Makefile for physical layer USB drivers
#
obj-$(CONFIG_USB_PHY)			+= phy.o
obj-$(CONFIG_OF)			+= of.o

# transceiver drivers, keep the list sorted

obj-$(CONFIG_NOP_USB_XCEIV)		+= phy-generic.o
